# Generated by Django 4.2.13 on 2026-03-17 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cutoff_time', models.TimeField()),
            ],
            options={
                'db_table': 'meal_types',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='MealOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='meals.mealtype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='meals.student')),
            ],
            options={
                'db_table': 'meal_orders',
                'indexes': [models.Index(fields=['student'], name='meal_orders_student_2fab13_idx'), models.Index(fields=['meal_type'], name='meal_orders_meal_ty_ea2a57_idx'), models.Index(fields=['status'], name='meal_orders_status_fc1fa4_idx')],
            },
        ),
    ]
