# Generated by Django 4.2.13 on 2026-03-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealorder',
            name='delivery_type',
            field=models.CharField(choices=[('takeaway', 'Takeaway'), ('delivery', 'Delivery')], default='takeaway', max_length=20),
        ),
        migrations.AddField(
            model_name='mealorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
