# Generated by Django 4.2.13 on 2026-03-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_mealorder_delivery_type_mealorder_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealorder',
            name='delivery_address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
