# Generated by Django 4.2.13 on 2026-03-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_mealorder_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealorder',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
