# Generated by Django 4.2.13 on 2026-03-21 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_mealorder_order_type_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealorder',
            name='student_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=30, unique=True)),
                ('source', models.CharField(choices=[('online', 'Online Order'), ('walk_in', 'Walk-in')], default='online', max_length=10)),
                ('items', models.JSONField(default=list)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sent_to_email', models.EmailField(blank=True, default='', max_length=254)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('meal_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill', to='meals.mealorder')),
            ],
            options={
                'db_table': 'bills',
                'ordering': ['-generated_at'],
            },
        ),
    ]
