# Generated by Django 4.2.13 on 2026-03-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0009_bill_and_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
