# Generated by Django 4.2.13 on 2026-03-21 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_add_customer_name_to_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealorder',
            name='meal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='meals.mealtype'),
        ),
    ]
