# Generated by Django 4.2.13 on 2026-03-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0011_alter_mealorder_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealorder',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36),
        ),
    ]
