# Generated by Django 4.2.13 on 2026-03-17 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('is_partner', models.BooleanField(default=False)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='PartnerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='partners.branch')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='partner_transaction', to='events.event')),
            ],
            options={
                'db_table': 'partner_transactions',
            },
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['is_partner'], name='branches_is_part_471d41_idx'),
        ),
        migrations.AddIndex(
            model_name='partnertransaction',
            index=models.Index(fields=['branch'], name='partner_tra_branch__5f74f5_idx'),
        ),
        migrations.AddIndex(
            model_name='partnertransaction',
            index=models.Index(fields=['event'], name='partner_tra_event_i_a984bf_idx'),
        ),
        migrations.AddIndex(
            model_name='partnertransaction',
            index=models.Index(fields=['status'], name='partner_tra_status_d314aa_idx'),
        ),
    ]
