# Generated by Django 4.2.13 on 2026-03-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(choices=[('meal', 'Meal'), ('pos', 'POS'), ('event', 'Event')], max_length=20)),
                ('reference_id', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payments',
                'indexes': [models.Index(fields=['reference_type', 'reference_id'], name='payments_referen_aaa5d3_idx')],
            },
        ),
    ]
