# Generated by Django 4.2.13 on 2026-04-12 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_pendingstudentregistration'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresetotp',
            new_name='authenticat_user_id_baaf4d_idx',
            old_name='authenticat_user_id_02adab_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresetotp',
            new_name='authenticat_used_at_12a8d1_idx',
            old_name='authenticat_used_at_f6549b_idx',
        ),
        migrations.RenameIndex(
            model_name='pendingstudentregistration',
            new_name='authenticat_email_869d90_idx',
            old_name='authenticat_email_319c25_idx',
        ),
        migrations.RenameIndex(
            model_name='pendingstudentregistration',
            new_name='authenticat_used_at_c90ab6_idx',
            old_name='authenticat_used_at_219fad_idx',
        ),
    ]
