# Generated by Django 4.2.13 on 2026-03-17 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='pos.category')),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='PosOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('voided', 'Voided')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pos_orders',
            },
        ),
        migrations.CreateModel(
            name='PosOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.item')),
                ('pos_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='pos.posorder')),
            ],
            options={
                'db_table': 'pos_order_items',
                'indexes': [models.Index(fields=['pos_order'], name='pos_order_i_pos_ord_9fccf0_idx'), models.Index(fields=['item'], name='pos_order_i_item_id_33c2c0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='posorder',
            index=models.Index(fields=['cashier'], name='pos_orders_cashier_8722a6_idx'),
        ),
        migrations.AddIndex(
            model_name='posorder',
            index=models.Index(fields=['status'], name='pos_orders_status_c62d41_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category'], name='items_categor_a72b5f_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_available'], name='items_is_avai_2577f6_idx'),
        ),
    ]
