# Generated by Django 4.2.13 on 2026-03-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
