# Generated by Django 4.2.13 on 2026-03-21 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_category_cascade_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured', to='pos.item')),
            ],
            options={
                'db_table': 'featured_items',
                'ordering': ['position'],
            },
        ),
    ]
