# Generated by Django 4.2.13 on 2026-03-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_featureditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('meal_time', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20)),
                ('meal_category', models.CharField(choices=[('veg', 'Veg'), ('nonveg', 'Non-Veg')], max_length=20)),
                ('dishes', models.JSONField(default=list)),
                ('price', models.DecimalField(decimal_places=2, default=200, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'weekly_meal_plan',
                'ordering': ['day_of_week', 'meal_time', 'meal_category'],
                'unique_together': {('day_of_week', 'meal_time', 'meal_category')},
            },
        ),
    ]
