# Generated by Django 4.2.13 on 2026-05-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_menuitem_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['item_id', 'name', 'id']},
        ),
        migrations.RenameIndex(
            model_name='itemvariant',
            new_name='item_varian_item_id_24f4d0_idx',
            old_name='item_varian_item_id_8ee62f_idx',
        ),
        migrations.RenameIndex(
            model_name='itemvariant',
            new_name='item_varian_is_acti_95e280_idx',
            old_name='item_varian_is_acti_6f4d6a_idx',
        ),
        migrations.RenameIndex(
            model_name='menuitem',
            new_name='menu_items_menu_gr_cd85a7_idx',
            old_name='menu_items_menu_gr_7f8a39_idx',
        ),
        migrations.RenameIndex(
            model_name='menuitem',
            new_name='menu_items_is_avai_013e6c_idx',
            old_name='menu_items_is_avai_767bcb_idx',
        ),
    ]
